name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    services:
      web:
        image: php:apache
        ports:
          - 80:80
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -U selenium pytest pytest-xdist
          sudo apt-get update
          sudo apt-get install -y firefox-geckodriver
          firefox --version
          geckodriver --version

      - name: Start Selenium server
        run: |
          docker run -d --network=host --name selenium-server selenium/standalone-firefox:latest

      - name: Wait for Selenium
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:4444/status | grep -q "READY"; then
              echo "Selenium is ready!"
              exit 0
            fi
            echo "Waiting for Selenium..."
            sleep 2
          done
          echo "Selenium did not start in time!" && exit 1

      - name: Set Environment Variables
        run: echo "URL=http://localhost" >> $GITHUB_ENV

      - name: Run Selenium Tests
        run: python test.py

      - name: Stop Selenium
        run: docker stop selenium-server
